liip_imagine:
    twig:
        mode: lazy
    resolvers:
        default:
            web_path:
                web_root: '%kernel.project_dir%/public'
                cache_prefix: 'media/cache'
    default_filter_set_settings:
        quality: 75

    filter_sets:
        cache: ~

        editPhotoItem:
            quality: 100
            filters:
                thumbnail: { size: [ 200, 200 ], mode: outbound }

        renderIntroItem:
            quality: 50
            filters:
                thumbnail: { size: [ 250, 300 ], mode: outbound }

        renderFullMainPhoto:
            quality: 65
            filters:
                relative_resize:
                    widen: 480

        renderFullPhoto:
            quality: 30
            filters:
                thumbnail: { size: [ 120, 120 ], mode: outbound }